services:
  - type: web
    name: bc-emergency-mgmt-map
    env: python
    region: eu-central-1
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    outboundNetwork:
      allowedDomains:
        - nominatim.openstreetmap.org
        - raw.githubusercontent.com
        - services6.arcgis.com